### ISSUE TITLE
보드가 출력되지 않는 오류

### ISSUE THREAD

**Issue by shuffle2479** [hhyein/project_tetris#57]
![image](https://user-images.githubusercontent.com/48901291/58635946-1c68b500-832a-11e9-896e-b257cc0f62ff.png)
기존 오픈소스는 위의 사진처럼 보드가 출력되지 않는 오류가 있습니다.
이 오류의 원인을 찾아보다가 visual studio 설정 문제라는 것을 알게 되었는데요.
그러면 오류라고 해야 할까요? 아니면 오류라고 하지 말아야 할까요?

**Comment by hhyein** [comment]
설정 문제니까 오류는 아닌 것 같네요.
보고서에 설정에 대한 설명만 적으면 될 것 같습니다.

**Comment by Jisue** [comment]
저도 찾아보니 레거시 콘솔을 이용해서 실행하면 괜찮더라구요
오류가 아니라고 해야하지 않을까요?
